---
title: "DS502- Final Project"
author: "Abhishek Shah, Mahdi Alouane and Rahul Pande"
output:
  html_document:
    df_print: paged
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      tidy=TRUE,
                      fig.align='center',
                      tidy.opts=list(width.cutoff=60))
# https://www.calvin.edu/~rpruim/courses/s341/S17/from-class/MathinRmd.html
```

### Exploratory Data Analysis

# Data Summary
```{r EDA 1}
train <- read.csv("./Train.csv")
dim(train)
str(train)
table(is.na(train))
colSums(is.na(train))
summary(train)
```
#Split the data
```{r EDA 2}
set.seed(502)
split <- sample(1:nrow(train),1000)
test <- train[split,]
train <- train[-split,]
```


# Imputing missing Item_Weight values in train
```{r EDA 3}
for (i in 1:nrow(train)) {
  if(is.na(train[i,]$Item_Weight)) {
    id <- train[i,]$Item_Identifier
    weight <- train[ train$Item_Identifier == id & !is.na(train$Item_Weight),]$Item_Weight[1]
    train[i,]$Item_Weight = weight
  }
}

train <- train[!is.na(train$Item_Weight),]

write.csv(train,'train_weight.csv')
```

# Imputing missing Item_Weight values in test
```{r EDA 4, warning=FALSE}
for (i in 1:nrow(test)) {
  if(is.na(test$Item_Weight)) {
    id <- test[i,]$Item_Identifier
    weight <- test[ test$Item_Identifier == id & !is.na(test$Item_Weight),]$Item_Weight[1]
    test[i,]$Item_Weight = weight
  }
}

test <- test[!is.na(test$Item_Weight),]

write.csv(train,'test_weight.csv')
```